[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_marketplace = "NFTMCFJD7ACCQr29CXeyqgMJe2HhdQJBDEMpSfTcqCk"

[programs.devnet]
solana_marketplace = "NFTMCFJD7ACCQr29CXeyqgMJe2HhdQJBDEMpSfTcqCk"

[programs.mainnet]
solana_marketplace = "NFTMCFJD7ACCQr29CXeyqgMJe2HhdQJBDEMpSfTcqCk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "keypair/NFT99UUrXCrtYfyAEgAnKPfh9sA3LtSP2sSDLmBW8UF.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
