[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_marketplace = "NFT51pLJ7BLm9U3yAcaAp6z3EoqnnvWBc7vHRYvsgi3"

[programs.devnet]
solana_marketplace = "NFT51pLJ7BLm9U3yAcaAp6z3EoqnnvWBc7vHRYvsgi3"

[programs.mainnet]
solana_marketplace = "NFT51pLJ7BLm9U3yAcaAp6z3EoqnnvWBc7vHRYvsgi3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://metaplex.devnet.rpcpool.com"
wallet = "keypair/NFT99UUrXCrtYfyAEgAnKPfh9sA3LtSP2sSDLmBW8UF.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
